# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tinkering and Dreaming
email: alaena.vandermost@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Build your dreams - color outside of the lines. It is never too late to learn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "alaenavandermost.com" # the base hostname & protocol for your site
twitter_username: westernmassive
github_username:  westernmassive

# Build settings
markdown: kramdown
